### ISSUE TITLE
C style {}

### ISSUE THREAD

**Issue by filkata** [sanbox-irl/gml_fmt#30]
I would really love it if you add the option to do C style braces {}
like so:
if (cond)
{
   statement;
}

**Comment by sanboxrunner** [comment]
Hi thanks! 

Right now, my plan is to not support alternative bracing styles for a few reasons
1. The biggest value of an autoformatter is in uniformity, both within an individuals coding style, and across a language. Having everyone use one style, even if you don't like it, is good.
2. Honestly, time. I don't have that much time to spend on this project at the moment.

If I get enough time, I'll look into making an option. You're not the first to ask.

If others see this and comment that they'd like it, I'll spend the time doing it.
